// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvF3TeFnZ2xu75EadgWxxBd8vTwPHMrbg',
    appId: '1:886415945511:web:a482809ead798266de0302',
    messagingSenderId: '886415945511',
    projectId: 'smart-bin-86227',
    authDomain: 'smart-bin-86227.firebaseapp.com',
    storageBucket: 'smart-bin-86227.appspot.com',
    measurementId: 'G-MT58ECCF54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuAc-Iy7jeoaBUHOmT5P49WcEdSwAD3fc',
    appId: '1:886415945511:android:d018aa216eba8336de0302',
    messagingSenderId: '886415945511',
    projectId: 'smart-bin-86227',
    storageBucket: 'smart-bin-86227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx1SPY5aADdesCO2mteUQZZLJT2-eiS-A',
    appId: '1:886415945511:ios:acfe4b943194b612de0302',
    messagingSenderId: '886415945511',
    projectId: 'smart-bin-86227',
    storageBucket: 'smart-bin-86227.appspot.com',
    iosClientId: '886415945511-l26pf97bm7n6l9e5timgb5qbf52moc94.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartbin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx1SPY5aADdesCO2mteUQZZLJT2-eiS-A',
    appId: '1:886415945511:ios:acfe4b943194b612de0302',
    messagingSenderId: '886415945511',
    projectId: 'smart-bin-86227',
    storageBucket: 'smart-bin-86227.appspot.com',
    iosClientId: '886415945511-l26pf97bm7n6l9e5timgb5qbf52moc94.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartbin',
  );
}
